# Site settings
name: Md Abdur Razzaq Riyadh
title: Razzaq | Machine Learning Engineer
description: An aspiring data scientist.
url: https://riyadhrazzaq.github.io/
baseurl: 'https://riyadhrazzaq.github.io'
email: riyadh.razzaq@gmail.com
cover: https://riyadhrazzaq.github.io/img/og.png
logo: https://riyadhrazzaq.github.io/img/emojis/technologist.png
resume: https://riyadhrazzaq.github.io/resume.pdf

social:
  - title: twitter
    url: https://twitter.com/riyadhrazzaq
  - title: github
    url: https://github.com/riyadhrazzaq
  - title: linkedin
    url: https://www.linkedin.com/in/md-abdur-razzaq-riyadh
  - title: kaggle
    url: https://kaggle.com/riyadhrazzaq
  - title: blog
    url: https://riyadhrazzaq.github.io/blog


# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

original_author:
  - url: https://bchiang7.github.io/
    name: Brittany Chiang